# Generated by Django 3.2 on 2021-04-12 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20210412_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='isVerified',
        ),
    ]
