# Generated by Django 3.2 on 2021-04-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20210412_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
