# Generated by Django 3.1.7 on 2021-04-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20210412_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='OTP',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
