# Generated by Django 3.1.7 on 2021-04-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_employee_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='OTP',
            field=models.IntegerField(default=0),
        ),
    ]
