# Generated by Django 3.1.7 on 2021-05-05 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_auto_20210418_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmployeeEmail',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeePhoneNum',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{11}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='OfficeID',
            field=models.IntegerField(unique=True),
        ),
    ]
