# Generated by Django 3.1.7 on 2021-05-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_remove_employee_officeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='OfficeID',
            field=models.IntegerField(default=1),
        ),
    ]
